using System;
using System.ComponentModel;
using System.Data;
using Cs_BuiltIn.Test_masterService;

namespace Cs_BuiltIn {

    /// <summary>
    /// Service client code (generated by DataTierGeneratorPlus), to call service client proxy reference (generated by Visual Studio / svcutil).
    /// </summary>
    public static class Test_masterServiceClientApplication
      {
        /// <summary>
        /// Sample service client application code
        /// </summary>
        public static void Test()
        {
            BindingListView<Test_masterService.Test_masterContract> masterList = default(BindingListView<Test_masterService.Test_masterContract>);
            //Test_masterService.Test_masterContract masterInfo = default(Test_masterService.Test_masterContract);
            Test_masterService.Test_masterServiceClient test_masterClient = new Test_masterService.Test_masterServiceClient();

            test_masterClient.Open();

            //call service methods here, using opened service client
            masterList = test_masterClient.SelectInfoAll().ToBindingListViewOfContract();

            if ((test_masterClient.State != System.ServiceModel.CommunicationState.Closed))
            {
                test_masterClient.Close();
            }
        }
      }

}
