'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Test_masterService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Test_masterContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Vb_BuiltIn_WcfServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Test_masterContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private notesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private someboolField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private somebool_nullableField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private somedateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private somedate_nullableField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private somefloatField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private somefloat_nullableField As System.Nullable(Of Double)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private someintField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private someint_nullableField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionField, value) <> true) Then
                    Me.descriptionField = value
                    Me.RaisePropertyChanged("description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.notesField, value) <> true) Then
                    Me.notesField = value
                    Me.RaisePropertyChanged("notes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somebool() As Boolean
            Get
                Return Me.someboolField
            End Get
            Set
                If (Me.someboolField.Equals(value) <> true) Then
                    Me.someboolField = value
                    Me.RaisePropertyChanged("somebool")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somebool_nullable() As System.Nullable(Of Boolean)
            Get
                Return Me.somebool_nullableField
            End Get
            Set
                If (Me.somebool_nullableField.Equals(value) <> true) Then
                    Me.somebool_nullableField = value
                    Me.RaisePropertyChanged("somebool_nullable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somedate() As Date
            Get
                Return Me.somedateField
            End Get
            Set
                If (Me.somedateField.Equals(value) <> true) Then
                    Me.somedateField = value
                    Me.RaisePropertyChanged("somedate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somedate_nullable() As System.Nullable(Of Date)
            Get
                Return Me.somedate_nullableField
            End Get
            Set
                If (Me.somedate_nullableField.Equals(value) <> true) Then
                    Me.somedate_nullableField = value
                    Me.RaisePropertyChanged("somedate_nullable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somefloat() As Double
            Get
                Return Me.somefloatField
            End Get
            Set
                If (Me.somefloatField.Equals(value) <> true) Then
                    Me.somefloatField = value
                    Me.RaisePropertyChanged("somefloat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property somefloat_nullable() As System.Nullable(Of Double)
            Get
                Return Me.somefloat_nullableField
            End Get
            Set
                If (Me.somefloat_nullableField.Equals(value) <> true) Then
                    Me.somefloat_nullableField = value
                    Me.RaisePropertyChanged("somefloat_nullable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property someint() As Integer
            Get
                Return Me.someintField
            End Get
            Set
                If (Me.someintField.Equals(value) <> true) Then
                    Me.someintField = value
                    Me.RaisePropertyChanged("someint")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property someint_nullable() As System.Nullable(Of Integer)
            Get
                Return Me.someint_nullableField
            End Get
            Set
                If (Me.someint_nullableField.Equals(value) <> true) Then
                    Me.someint_nullableField = value
                    Me.RaisePropertyChanged("someint_nullable")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Test_masterService.ITest_masterService")>  _
    Public Interface ITest_masterService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/Insert", ReplyAction:="http://tempuri.org/ITest_masterService/InsertResponse")>  _
        Sub Insert(ByVal id As Integer, ByVal description As String, ByVal notes As String, ByVal someint As Integer, ByVal someint_nullable As System.Nullable(Of Integer), ByVal somedate As Date, ByVal somedate_nullable As System.Nullable(Of Date), ByVal somefloat As Double, ByVal somefloat_nullable As System.Nullable(Of Double), ByVal somebool As Boolean, ByVal somebool_nullable As System.Nullable(Of Boolean))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/InsertInfo", ReplyAction:="http://tempuri.org/ITest_masterService/InsertInfoResponse")>  _
        Sub InsertInfo(ByVal info As Test_masterService.Test_masterContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/Update", ReplyAction:="http://tempuri.org/ITest_masterService/UpdateResponse")>  _
        Sub Update(ByVal id As Integer, ByVal description As String, ByVal notes As String, ByVal someint As Integer, ByVal someint_nullable As System.Nullable(Of Integer), ByVal somedate As Date, ByVal somedate_nullable As System.Nullable(Of Date), ByVal somefloat As Double, ByVal somefloat_nullable As System.Nullable(Of Double), ByVal somebool As Boolean, ByVal somebool_nullable As System.Nullable(Of Boolean))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/UpdateInfo", ReplyAction:="http://tempuri.org/ITest_masterService/UpdateInfoResponse")>  _
        Sub UpdateInfo(ByVal info As Test_masterService.Test_masterContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/Delete", ReplyAction:="http://tempuri.org/ITest_masterService/DeleteResponse")>  _
        Sub Delete(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/DeleteInfo", ReplyAction:="http://tempuri.org/ITest_masterService/DeleteInfoResponse")>  _
        Sub DeleteInfo(ByVal info As Test_masterService.Test_masterContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/SelectDS", ReplyAction:="http://tempuri.org/ITest_masterService/SelectDSResponse")>  _
        Function SelectDS(ByVal id As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/SelectInfo", ReplyAction:="http://tempuri.org/ITest_masterService/SelectInfoResponse")>  _
        Function SelectInfo(ByVal info As Test_masterService.Test_masterContract) As Test_masterService.Test_masterContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/SelectDSAll", ReplyAction:="http://tempuri.org/ITest_masterService/SelectDSAllResponse")>  _
        Function SelectDSAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_masterService/SelectInfoAll", ReplyAction:="http://tempuri.org/ITest_masterService/SelectInfoAllResponse")>  _
        Function SelectInfoAll() As Test_masterService.Test_masterContract()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITest_masterServiceChannel
        Inherits Test_masterService.ITest_masterService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Test_masterServiceClient
        Inherits System.ServiceModel.ClientBase(Of Test_masterService.ITest_masterService)
        Implements Test_masterService.ITest_masterService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Insert(ByVal id As Integer, ByVal description As String, ByVal notes As String, ByVal someint As Integer, ByVal someint_nullable As System.Nullable(Of Integer), ByVal somedate As Date, ByVal somedate_nullable As System.Nullable(Of Date), ByVal somefloat As Double, ByVal somefloat_nullable As System.Nullable(Of Double), ByVal somebool As Boolean, ByVal somebool_nullable As System.Nullable(Of Boolean)) Implements Test_masterService.ITest_masterService.Insert
            MyBase.Channel.Insert(id, description, notes, someint, someint_nullable, somedate, somedate_nullable, somefloat, somefloat_nullable, somebool, somebool_nullable)
        End Sub
        
        Public Sub InsertInfo(ByVal info As Test_masterService.Test_masterContract) Implements Test_masterService.ITest_masterService.InsertInfo
            MyBase.Channel.InsertInfo(info)
        End Sub
        
        Public Sub Update(ByVal id As Integer, ByVal description As String, ByVal notes As String, ByVal someint As Integer, ByVal someint_nullable As System.Nullable(Of Integer), ByVal somedate As Date, ByVal somedate_nullable As System.Nullable(Of Date), ByVal somefloat As Double, ByVal somefloat_nullable As System.Nullable(Of Double), ByVal somebool As Boolean, ByVal somebool_nullable As System.Nullable(Of Boolean)) Implements Test_masterService.ITest_masterService.Update
            MyBase.Channel.Update(id, description, notes, someint, someint_nullable, somedate, somedate_nullable, somefloat, somefloat_nullable, somebool, somebool_nullable)
        End Sub
        
        Public Sub UpdateInfo(ByVal info As Test_masterService.Test_masterContract) Implements Test_masterService.ITest_masterService.UpdateInfo
            MyBase.Channel.UpdateInfo(info)
        End Sub
        
        Public Sub Delete(ByVal id As Integer) Implements Test_masterService.ITest_masterService.Delete
            MyBase.Channel.Delete(id)
        End Sub
        
        Public Sub DeleteInfo(ByVal info As Test_masterService.Test_masterContract) Implements Test_masterService.ITest_masterService.DeleteInfo
            MyBase.Channel.DeleteInfo(info)
        End Sub
        
        Public Function SelectDS(ByVal id As Integer) As System.Data.DataSet Implements Test_masterService.ITest_masterService.SelectDS
            Return MyBase.Channel.SelectDS(id)
        End Function
        
        Public Function SelectInfo(ByVal info As Test_masterService.Test_masterContract) As Test_masterService.Test_masterContract() Implements Test_masterService.ITest_masterService.SelectInfo
            Return MyBase.Channel.SelectInfo(info)
        End Function
        
        Public Function SelectDSAll() As System.Data.DataSet Implements Test_masterService.ITest_masterService.SelectDSAll
            Return MyBase.Channel.SelectDSAll
        End Function
        
        Public Function SelectInfoAll() As Test_masterService.Test_masterContract() Implements Test_masterService.ITest_masterService.SelectInfoAll
            Return MyBase.Channel.SelectInfoAll
        End Function
    End Class
End Namespace
