//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_BuiltIn.Test_masterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Test_masterContract", Namespace="http://schemas.datacontract.org/2004/07/Cs_BuiltIn_WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class Test_masterContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool someboolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> somebool_nullableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime somedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> somedate_nullableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double somefloatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> somefloat_nullableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int someintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> someint_nullableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool somebool {
            get {
                return this.someboolField;
            }
            set {
                if ((this.someboolField.Equals(value) != true)) {
                    this.someboolField = value;
                    this.RaisePropertyChanged("somebool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> somebool_nullable {
            get {
                return this.somebool_nullableField;
            }
            set {
                if ((this.somebool_nullableField.Equals(value) != true)) {
                    this.somebool_nullableField = value;
                    this.RaisePropertyChanged("somebool_nullable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime somedate {
            get {
                return this.somedateField;
            }
            set {
                if ((this.somedateField.Equals(value) != true)) {
                    this.somedateField = value;
                    this.RaisePropertyChanged("somedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> somedate_nullable {
            get {
                return this.somedate_nullableField;
            }
            set {
                if ((this.somedate_nullableField.Equals(value) != true)) {
                    this.somedate_nullableField = value;
                    this.RaisePropertyChanged("somedate_nullable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double somefloat {
            get {
                return this.somefloatField;
            }
            set {
                if ((this.somefloatField.Equals(value) != true)) {
                    this.somefloatField = value;
                    this.RaisePropertyChanged("somefloat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> somefloat_nullable {
            get {
                return this.somefloat_nullableField;
            }
            set {
                if ((this.somefloat_nullableField.Equals(value) != true)) {
                    this.somefloat_nullableField = value;
                    this.RaisePropertyChanged("somefloat_nullable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int someint {
            get {
                return this.someintField;
            }
            set {
                if ((this.someintField.Equals(value) != true)) {
                    this.someintField = value;
                    this.RaisePropertyChanged("someint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> someint_nullable {
            get {
                return this.someint_nullableField;
            }
            set {
                if ((this.someint_nullableField.Equals(value) != true)) {
                    this.someint_nullableField = value;
                    this.RaisePropertyChanged("someint_nullable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Test_masterService.ITest_masterService")]
    public interface ITest_masterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/Insert", ReplyAction="http://tempuri.org/ITest_masterService/InsertResponse")]
        void Insert(int id, string description, string notes, int someint, System.Nullable<int> someint_nullable, System.DateTime somedate, System.Nullable<System.DateTime> somedate_nullable, double somefloat, System.Nullable<double> somefloat_nullable, bool somebool, System.Nullable<bool> somebool_nullable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/InsertInfo", ReplyAction="http://tempuri.org/ITest_masterService/InsertInfoResponse")]
        void InsertInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/Update", ReplyAction="http://tempuri.org/ITest_masterService/UpdateResponse")]
        void Update(int id, string description, string notes, int someint, System.Nullable<int> someint_nullable, System.DateTime somedate, System.Nullable<System.DateTime> somedate_nullable, double somefloat, System.Nullable<double> somefloat_nullable, bool somebool, System.Nullable<bool> somebool_nullable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/UpdateInfo", ReplyAction="http://tempuri.org/ITest_masterService/UpdateInfoResponse")]
        void UpdateInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/Delete", ReplyAction="http://tempuri.org/ITest_masterService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/DeleteInfo", ReplyAction="http://tempuri.org/ITest_masterService/DeleteInfoResponse")]
        void DeleteInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/SelectDS", ReplyAction="http://tempuri.org/ITest_masterService/SelectDSResponse")]
        System.Data.DataSet SelectDS(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/SelectInfo", ReplyAction="http://tempuri.org/ITest_masterService/SelectInfoResponse")]
        Cs_BuiltIn.Test_masterService.Test_masterContract[] SelectInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/SelectDSAll", ReplyAction="http://tempuri.org/ITest_masterService/SelectDSAllResponse")]
        System.Data.DataSet SelectDSAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_masterService/SelectInfoAll", ReplyAction="http://tempuri.org/ITest_masterService/SelectInfoAllResponse")]
        Cs_BuiltIn.Test_masterService.Test_masterContract[] SelectInfoAll();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITest_masterServiceChannel : Cs_BuiltIn.Test_masterService.ITest_masterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Test_masterServiceClient : System.ServiceModel.ClientBase<Cs_BuiltIn.Test_masterService.ITest_masterService>, Cs_BuiltIn.Test_masterService.ITest_masterService {
        
        public Test_masterServiceClient() {
        }
        
        public Test_masterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Test_masterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_masterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_masterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(int id, string description, string notes, int someint, System.Nullable<int> someint_nullable, System.DateTime somedate, System.Nullable<System.DateTime> somedate_nullable, double somefloat, System.Nullable<double> somefloat_nullable, bool somebool, System.Nullable<bool> somebool_nullable) {
            base.Channel.Insert(id, description, notes, someint, someint_nullable, somedate, somedate_nullable, somefloat, somefloat_nullable, somebool, somebool_nullable);
        }
        
        public void InsertInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info) {
            base.Channel.InsertInfo(info);
        }
        
        public void Update(int id, string description, string notes, int someint, System.Nullable<int> someint_nullable, System.DateTime somedate, System.Nullable<System.DateTime> somedate_nullable, double somefloat, System.Nullable<double> somefloat_nullable, bool somebool, System.Nullable<bool> somebool_nullable) {
            base.Channel.Update(id, description, notes, someint, someint_nullable, somedate, somedate_nullable, somefloat, somefloat_nullable, somebool, somebool_nullable);
        }
        
        public void UpdateInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info) {
            base.Channel.UpdateInfo(info);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public void DeleteInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info) {
            base.Channel.DeleteInfo(info);
        }
        
        public System.Data.DataSet SelectDS(int id) {
            return base.Channel.SelectDS(id);
        }
        
        public Cs_BuiltIn.Test_masterService.Test_masterContract[] SelectInfo(Cs_BuiltIn.Test_masterService.Test_masterContract info) {
            return base.Channel.SelectInfo(info);
        }
        
        public System.Data.DataSet SelectDSAll() {
            return base.Channel.SelectDSAll();
        }
        
        public Cs_BuiltIn.Test_masterService.Test_masterContract[] SelectInfoAll() {
            return base.Channel.SelectInfoAll();
        }
    }
}
