'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Test_detailService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Test_detailContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Vb_BuiltIn_WcfServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Test_detailContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private amtField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private master_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private qtyField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property amt() As Double
            Get
                Return Me.amtField
            End Get
            Set
                If (Me.amtField.Equals(value) <> true) Then
                    Me.amtField = value
                    Me.RaisePropertyChanged("amt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionField, value) <> true) Then
                    Me.descriptionField = value
                    Me.RaisePropertyChanged("description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                If (Object.ReferenceEquals(Me.idField, value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property master_id() As Integer
            Get
                Return Me.master_idField
            End Get
            Set
                If (Me.master_idField.Equals(value) <> true) Then
                    Me.master_idField = value
                    Me.RaisePropertyChanged("master_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property qty() As Integer
            Get
                Return Me.qtyField
            End Get
            Set
                If (Me.qtyField.Equals(value) <> true) Then
                    Me.qtyField = value
                    Me.RaisePropertyChanged("qty")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Test_detailService.ITest_detailService")>  _
    Public Interface ITest_detailService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/Insert", ReplyAction:="http://tempuri.org/ITest_detailService/InsertResponse")>  _
        Sub Insert(ByVal master_id As Integer, ByVal id As String, ByVal description As String, ByVal qty As Integer, ByVal amt As Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/InsertInfo", ReplyAction:="http://tempuri.org/ITest_detailService/InsertInfoResponse")>  _
        Sub InsertInfo(ByVal info As Test_detailService.Test_detailContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/Update", ReplyAction:="http://tempuri.org/ITest_detailService/UpdateResponse")>  _
        Sub Update(ByVal master_id As Integer, ByVal id As String, ByVal description As String, ByVal qty As Integer, ByVal amt As Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/UpdateInfo", ReplyAction:="http://tempuri.org/ITest_detailService/UpdateInfoResponse")>  _
        Sub UpdateInfo(ByVal info As Test_detailService.Test_detailContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/Delete", ReplyAction:="http://tempuri.org/ITest_detailService/DeleteResponse")>  _
        Sub Delete(ByVal master_id As Integer, ByVal id As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/DeleteInfo", ReplyAction:="http://tempuri.org/ITest_detailService/DeleteInfoResponse")>  _
        Sub DeleteInfo(ByVal info As Test_detailService.Test_detailContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/DeleteByMaster_id", ReplyAction:="http://tempuri.org/ITest_detailService/DeleteByMaster_idResponse")>  _
        Sub DeleteByMaster_id(ByVal master_id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/DeleteInfoByMaster_id", ReplyAction:="http://tempuri.org/ITest_detailService/DeleteInfoByMaster_idResponse")>  _
        Sub DeleteInfoByMaster_id(ByVal info As Test_detailService.Test_detailContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectDS", ReplyAction:="http://tempuri.org/ITest_detailService/SelectDSResponse")>  _
        Function SelectDS(ByVal master_id As Integer, ByVal id As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectInfo", ReplyAction:="http://tempuri.org/ITest_detailService/SelectInfoResponse")>  _
        Function SelectInfo(ByVal info As Test_detailService.Test_detailContract) As Test_detailService.Test_detailContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectDSAll", ReplyAction:="http://tempuri.org/ITest_detailService/SelectDSAllResponse")>  _
        Function SelectDSAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectInfoAll", ReplyAction:="http://tempuri.org/ITest_detailService/SelectInfoAllResponse")>  _
        Function SelectInfoAll() As Test_detailService.Test_detailContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectDSByMaster_id", ReplyAction:="http://tempuri.org/ITest_detailService/SelectDSByMaster_idResponse")>  _
        Function SelectDSByMaster_id(ByVal master_id As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITest_detailService/SelectInfoByMaster_id", ReplyAction:="http://tempuri.org/ITest_detailService/SelectInfoByMaster_idResponse")>  _
        Function SelectInfoByMaster_id(ByVal info As Test_detailService.Test_detailContract) As Test_detailService.Test_detailContract()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITest_detailServiceChannel
        Inherits Test_detailService.ITest_detailService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Test_detailServiceClient
        Inherits System.ServiceModel.ClientBase(Of Test_detailService.ITest_detailService)
        Implements Test_detailService.ITest_detailService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Insert(ByVal master_id As Integer, ByVal id As String, ByVal description As String, ByVal qty As Integer, ByVal amt As Double) Implements Test_detailService.ITest_detailService.Insert
            MyBase.Channel.Insert(master_id, id, description, qty, amt)
        End Sub
        
        Public Sub InsertInfo(ByVal info As Test_detailService.Test_detailContract) Implements Test_detailService.ITest_detailService.InsertInfo
            MyBase.Channel.InsertInfo(info)
        End Sub
        
        Public Sub Update(ByVal master_id As Integer, ByVal id As String, ByVal description As String, ByVal qty As Integer, ByVal amt As Double) Implements Test_detailService.ITest_detailService.Update
            MyBase.Channel.Update(master_id, id, description, qty, amt)
        End Sub
        
        Public Sub UpdateInfo(ByVal info As Test_detailService.Test_detailContract) Implements Test_detailService.ITest_detailService.UpdateInfo
            MyBase.Channel.UpdateInfo(info)
        End Sub
        
        Public Sub Delete(ByVal master_id As Integer, ByVal id As String) Implements Test_detailService.ITest_detailService.Delete
            MyBase.Channel.Delete(master_id, id)
        End Sub
        
        Public Sub DeleteInfo(ByVal info As Test_detailService.Test_detailContract) Implements Test_detailService.ITest_detailService.DeleteInfo
            MyBase.Channel.DeleteInfo(info)
        End Sub
        
        Public Sub DeleteByMaster_id(ByVal master_id As Integer) Implements Test_detailService.ITest_detailService.DeleteByMaster_id
            MyBase.Channel.DeleteByMaster_id(master_id)
        End Sub
        
        Public Sub DeleteInfoByMaster_id(ByVal info As Test_detailService.Test_detailContract) Implements Test_detailService.ITest_detailService.DeleteInfoByMaster_id
            MyBase.Channel.DeleteInfoByMaster_id(info)
        End Sub
        
        Public Function SelectDS(ByVal master_id As Integer, ByVal id As String) As System.Data.DataSet Implements Test_detailService.ITest_detailService.SelectDS
            Return MyBase.Channel.SelectDS(master_id, id)
        End Function
        
        Public Function SelectInfo(ByVal info As Test_detailService.Test_detailContract) As Test_detailService.Test_detailContract() Implements Test_detailService.ITest_detailService.SelectInfo
            Return MyBase.Channel.SelectInfo(info)
        End Function
        
        Public Function SelectDSAll() As System.Data.DataSet Implements Test_detailService.ITest_detailService.SelectDSAll
            Return MyBase.Channel.SelectDSAll
        End Function
        
        Public Function SelectInfoAll() As Test_detailService.Test_detailContract() Implements Test_detailService.ITest_detailService.SelectInfoAll
            Return MyBase.Channel.SelectInfoAll
        End Function
        
        Public Function SelectDSByMaster_id(ByVal master_id As Integer) As System.Data.DataSet Implements Test_detailService.ITest_detailService.SelectDSByMaster_id
            Return MyBase.Channel.SelectDSByMaster_id(master_id)
        End Function
        
        Public Function SelectInfoByMaster_id(ByVal info As Test_detailService.Test_detailContract) As Test_detailService.Test_detailContract() Implements Test_detailService.ITest_detailService.SelectInfoByMaster_id
            Return MyBase.Channel.SelectInfoByMaster_id(info)
        End Function
    End Class
End Namespace
