Imports System
Imports System.ComponentModel
Imports System.Data
Imports VB_BuiltIn.Test_detailService

Namespace VB_BuiltIn 

    ''' <summary>
    ''' Service client code (generated by DataTierGeneratorPlus), to call service client proxy reference (generated by Visual Studio / svcutil).
    ''' </summary>
    Public NotInheritable Class Test_detailServiceClientApplication
        Private Sub New()
        End Sub
        ''' <summary>
        ''' Sample service client application code
        ''' </summary>
        Public Shared Sub Test()
            Dim masterList As BindingListView(Of Test_detailService.Test_detailContract) = Nothing
            'Test_detailService.Test_detailContract masterInfo = default(Test_detailService.Test_detailContract);
            Dim test_detailClient As New Test_detailService.Test_detailServiceClient()

            test_detailClient.Open()

            'call service methods here, using opened service client
            masterList = test_detailClient.SelectInfoAll().ToBindingListViewOfContract()

            If (test_detailClient.State <> System.ServiceModel.CommunicationState.Closed) Then
                test_detailClient.Close()
            End If
        End Sub
    End Class

End Namespace
