Imports System
Imports System.ComponentModel
Imports System.Data
Imports VB_BuiltIn.Test_masterService

Namespace VB_BuiltIn 

    ''' <summary>
    ''' Service client code (generated by DataTierGeneratorPlus), to call service client proxy reference (generated by Visual Studio / svcutil).
    ''' </summary>
    Public NotInheritable Class Test_masterServiceClientApplication
        Private Sub New()
        End Sub
        ''' <summary>
        ''' Sample service client application code
        ''' </summary>
        Public Shared Sub Test()
            Dim masterList As BindingListView(Of Test_masterService.Test_masterContract) = Nothing
            'Test_masterService.Test_masterContract masterInfo = default(Test_masterService.Test_masterContract);
            Dim test_masterClient As New Test_masterService.Test_masterServiceClient()

            test_masterClient.Open()

            'call service methods here, using opened service client
            masterList = test_masterClient.SelectInfoAll().ToBindingListViewOfContract()

            If (test_masterClient.State <> System.ServiceModel.CommunicationState.Closed) Then
                test_masterClient.Close()
            End If
        End Sub
    End Class

End Namespace
