//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_BuiltIn.Test_detailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Test_detailContract", Namespace="http://schemas.datacontract.org/2004/07/Cs_BuiltIn_WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class Test_detailContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int master_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amt {
            get {
                return this.amtField;
            }
            set {
                if ((this.amtField.Equals(value) != true)) {
                    this.amtField = value;
                    this.RaisePropertyChanged("amt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int master_id {
            get {
                return this.master_idField;
            }
            set {
                if ((this.master_idField.Equals(value) != true)) {
                    this.master_idField = value;
                    this.RaisePropertyChanged("master_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Test_detailService.ITest_detailService")]
    public interface ITest_detailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/Insert", ReplyAction="http://tempuri.org/ITest_detailService/InsertResponse")]
        void Insert(int master_id, string id, string description, int qty, double amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/InsertInfo", ReplyAction="http://tempuri.org/ITest_detailService/InsertInfoResponse")]
        void InsertInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/Update", ReplyAction="http://tempuri.org/ITest_detailService/UpdateResponse")]
        void Update(int master_id, string id, string description, int qty, double amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/UpdateInfo", ReplyAction="http://tempuri.org/ITest_detailService/UpdateInfoResponse")]
        void UpdateInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/Delete", ReplyAction="http://tempuri.org/ITest_detailService/DeleteResponse")]
        void Delete(int master_id, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/DeleteInfo", ReplyAction="http://tempuri.org/ITest_detailService/DeleteInfoResponse")]
        void DeleteInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/DeleteByMaster_id", ReplyAction="http://tempuri.org/ITest_detailService/DeleteByMaster_idResponse")]
        void DeleteByMaster_id(int master_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/DeleteInfoByMaster_id", ReplyAction="http://tempuri.org/ITest_detailService/DeleteInfoByMaster_idResponse")]
        void DeleteInfoByMaster_id(Cs_BuiltIn.Test_detailService.Test_detailContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectDS", ReplyAction="http://tempuri.org/ITest_detailService/SelectDSResponse")]
        System.Data.DataSet SelectDS(int master_id, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectInfo", ReplyAction="http://tempuri.org/ITest_detailService/SelectInfoResponse")]
        Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectDSAll", ReplyAction="http://tempuri.org/ITest_detailService/SelectDSAllResponse")]
        System.Data.DataSet SelectDSAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectInfoAll", ReplyAction="http://tempuri.org/ITest_detailService/SelectInfoAllResponse")]
        Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfoAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectDSByMaster_id", ReplyAction="http://tempuri.org/ITest_detailService/SelectDSByMaster_idResponse")]
        System.Data.DataSet SelectDSByMaster_id(int master_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest_detailService/SelectInfoByMaster_id", ReplyAction="http://tempuri.org/ITest_detailService/SelectInfoByMaster_idResponse")]
        Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfoByMaster_id(Cs_BuiltIn.Test_detailService.Test_detailContract info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITest_detailServiceChannel : Cs_BuiltIn.Test_detailService.ITest_detailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Test_detailServiceClient : System.ServiceModel.ClientBase<Cs_BuiltIn.Test_detailService.ITest_detailService>, Cs_BuiltIn.Test_detailService.ITest_detailService {
        
        public Test_detailServiceClient() {
        }
        
        public Test_detailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Test_detailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_detailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_detailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(int master_id, string id, string description, int qty, double amt) {
            base.Channel.Insert(master_id, id, description, qty, amt);
        }
        
        public void InsertInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            base.Channel.InsertInfo(info);
        }
        
        public void Update(int master_id, string id, string description, int qty, double amt) {
            base.Channel.Update(master_id, id, description, qty, amt);
        }
        
        public void UpdateInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            base.Channel.UpdateInfo(info);
        }
        
        public void Delete(int master_id, string id) {
            base.Channel.Delete(master_id, id);
        }
        
        public void DeleteInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            base.Channel.DeleteInfo(info);
        }
        
        public void DeleteByMaster_id(int master_id) {
            base.Channel.DeleteByMaster_id(master_id);
        }
        
        public void DeleteInfoByMaster_id(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            base.Channel.DeleteInfoByMaster_id(info);
        }
        
        public System.Data.DataSet SelectDS(int master_id, string id) {
            return base.Channel.SelectDS(master_id, id);
        }
        
        public Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfo(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            return base.Channel.SelectInfo(info);
        }
        
        public System.Data.DataSet SelectDSAll() {
            return base.Channel.SelectDSAll();
        }
        
        public Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfoAll() {
            return base.Channel.SelectInfoAll();
        }
        
        public System.Data.DataSet SelectDSByMaster_id(int master_id) {
            return base.Channel.SelectDSByMaster_id(master_id);
        }
        
        public Cs_BuiltIn.Test_detailService.Test_detailContract[] SelectInfoByMaster_id(Cs_BuiltIn.Test_detailService.Test_detailContract info) {
            return base.Channel.SelectInfoByMaster_id(info);
        }
    }
}
